### ISSUE TITLE
strange code, line 352 at the method do_insert of the file storage.rb

### ISSUE THREAD

**Issue by chaofan** [jmettraux/ruote-sequel#5]
```
    doc = doc.send(
      update_rev ? :merge! : :merge,
      {'_rev' => rev, 'put_at' => Ruote.now_to_utc_s}
    )
```
# means?

doc.merge!({'_rev' => rev, 'put_at' => Ruote.now_to_utc_s}) if update_rev
# 

doc is the same whatever the update_rev is,  true or not

**Comment by jmettraux** [comment]
Hello Chaofan,

if update_rev is true, then doc is the original doc, if update_rev is false, then doc is a copy of the original doc (since merge and merge! are well not same thing).

The motivation: https://github.com/jmettraux/ruote/blob/master/test/functional/storage.rb#L181-214

This 'update_rev' thing introduces a small side effect (when it's true, the doc passed to #put is modified (thanks to merge!)).

I hope this will help. Best regards,
